// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAgencySystem.Models;

#nullable disable

namespace RealEstateAgencySystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250317083131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("RealEstateAgencySystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ContactAddress = "1580 B St, West Vancouver, BC, Canada",
                            Email = "customer1@example.com",
                            Name = "John Smith",
                            Password = "Password123!",
                            Phone = "827-383-2545",
                            PostalCode = "V9P8L6"
                        },
                        new
                        {
                            CustomerId = 2,
                            ContactAddress = "159 K St, Vancouver, BC, Canada",
                            Email = "customer2@example.com",
                            Name = "Emily Johnson",
                            Password = "Password123!",
                            Phone = "777-839-4397",
                            PostalCode = "V7M3R6"
                        },
                        new
                        {
                            CustomerId = 3,
                            ContactAddress = "8846 D St, Delta, BC, Canada",
                            Email = "customer3@example.com",
                            Name = "Michael Williams",
                            Password = "Password123!",
                            Phone = "981-572-3074",
                            PostalCode = "V7B1I7"
                        },
                        new
                        {
                            CustomerId = 4,
                            ContactAddress = "6552 R St, New Westminster, BC, Canada",
                            Email = "customer4@example.com",
                            Name = "Sarah Brown",
                            Password = "Password123!",
                            Phone = "109-986-6177",
                            PostalCode = "V8D9E6"
                        },
                        new
                        {
                            CustomerId = 5,
                            ContactAddress = "6957 D St, North Vancouver, BC, Canada",
                            Email = "customer5@example.com",
                            Name = "David Miller",
                            Password = "Password123!",
                            Phone = "599-936-1292",
                            PostalCode = "V5K3Z3"
                        },
                        new
                        {
                            CustomerId = 6,
                            ContactAddress = "6621 M St, Langley, BC, Canada",
                            Email = "customer6@example.com",
                            Name = "Jessica Davis",
                            Password = "Password123!",
                            Phone = "185-653-7655",
                            PostalCode = "V7M3W2"
                        },
                        new
                        {
                            CustomerId = 7,
                            ContactAddress = "4494 P St, Richmond, BC, Canada",
                            Email = "customer7@example.com",
                            Name = "James Wilson",
                            Password = "Password123!",
                            Phone = "840-736-4269",
                            PostalCode = "V9B6O4"
                        },
                        new
                        {
                            CustomerId = 8,
                            ContactAddress = "9084 E St, West Vancouver, BC, Canada",
                            Email = "customer8@example.com",
                            Name = "Laura Martinez",
                            Password = "Password123!",
                            Phone = "764-993-5958",
                            PostalCode = "V8Z4L5"
                        },
                        new
                        {
                            CustomerId = 9,
                            ContactAddress = "7654 H St, Vancouver, BC, Canada",
                            Email = "customer9@example.com",
                            Name = "Robert Anderson",
                            Password = "Password123!",
                            Phone = "946-591-6741",
                            PostalCode = "V2U6W5"
                        },
                        new
                        {
                            CustomerId = 10,
                            ContactAddress = "1565 I St, Vancouver, BC, Canada",
                            Email = "customer10@example.com",
                            Name = "Sophia Thomas",
                            Password = "Password123!",
                            Phone = "190-675-6167",
                            PostalCode = "V7A1K2"
                        },
                        new
                        {
                            CustomerId = 11,
                            ContactAddress = "2556 W St, Langley, BC, Canada",
                            Email = "customer11@example.com",
                            Name = "Daniel Taylor",
                            Password = "Password123!",
                            Phone = "664-864-6435",
                            PostalCode = "V2E2P3"
                        },
                        new
                        {
                            CustomerId = 12,
                            ContactAddress = "5220 E St, Vancouver, BC, Canada",
                            Email = "customer12@example.com",
                            Name = "Olivia Moore",
                            Password = "Password123!",
                            Phone = "933-149-5858",
                            PostalCode = "V3G3T6"
                        },
                        new
                        {
                            CustomerId = 13,
                            ContactAddress = "9561 T St, Vancouver, BC, Canada",
                            Email = "customer13@example.com",
                            Name = "Matthew Jackson",
                            Password = "Password123!",
                            Phone = "325-402-5943",
                            PostalCode = "V1N8M7"
                        },
                        new
                        {
                            CustomerId = 14,
                            ContactAddress = "8281 R St, North Vancouver, BC, Canada",
                            Email = "customer14@example.com",
                            Name = "Isabella White",
                            Password = "Password123!",
                            Phone = "481-836-6170",
                            PostalCode = "V9Y4H8"
                        },
                        new
                        {
                            CustomerId = 15,
                            ContactAddress = "1552 V St, Langley, BC, Canada",
                            Email = "customer15@example.com",
                            Name = "Christopher Harris",
                            Password = "Password123!",
                            Phone = "134-688-7724",
                            PostalCode = "V5S8M1"
                        },
                        new
                        {
                            CustomerId = 16,
                            ContactAddress = "5004 M St, Coquitlam, BC, Canada",
                            Email = "customer16@example.com",
                            Name = "Emma Martin",
                            Password = "Password123!",
                            Phone = "789-687-7689",
                            PostalCode = "V2Q8H1"
                        },
                        new
                        {
                            CustomerId = 17,
                            ContactAddress = "9310 B St, New Westminster, BC, Canada",
                            Email = "customer17@example.com",
                            Name = "Joshua Thompson",
                            Password = "Password123!",
                            Phone = "902-873-9618",
                            PostalCode = "V8G1I7"
                        },
                        new
                        {
                            CustomerId = 18,
                            ContactAddress = "8958 H St, West Vancouver, BC, Canada",
                            Email = "customer18@example.com",
                            Name = "Ava Garcia",
                            Password = "Password123!",
                            Phone = "377-700-8288",
                            PostalCode = "V3F1G7"
                        },
                        new
                        {
                            CustomerId = 19,
                            ContactAddress = "1798 J St, Langley, BC, Canada",
                            Email = "customer19@example.com",
                            Name = "Andrew Lee",
                            Password = "Password123!",
                            Phone = "257-456-9090",
                            PostalCode = "V6B1V1"
                        },
                        new
                        {
                            CustomerId = 20,
                            ContactAddress = "2104 P St, North Vancouver, BC, Canada",
                            Email = "customer20@example.com",
                            Name = "Mia Robinson",
                            Password = "Password123!",
                            Phone = "301-676-6805",
                            PostalCode = "V6T3K9"
                        });
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            ContentType = "image/jpeg",
                            FileName = "property_1_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 1
                        },
                        new
                        {
                            ImageID = 2,
                            ContentType = "image/jpeg",
                            FileName = "property_1_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 1
                        },
                        new
                        {
                            ImageID = 3,
                            ContentType = "image/jpeg",
                            FileName = "property_1_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 1
                        },
                        new
                        {
                            ImageID = 4,
                            ContentType = "image/jpeg",
                            FileName = "property_2_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 2
                        },
                        new
                        {
                            ImageID = 5,
                            ContentType = "image/jpeg",
                            FileName = "property_2_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 2
                        },
                        new
                        {
                            ImageID = 6,
                            ContentType = "image/jpeg",
                            FileName = "property_2_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 2
                        },
                        new
                        {
                            ImageID = 7,
                            ContentType = "image/jpeg",
                            FileName = "property_3_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 3
                        },
                        new
                        {
                            ImageID = 8,
                            ContentType = "image/jpeg",
                            FileName = "property_3_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 3
                        },
                        new
                        {
                            ImageID = 9,
                            ContentType = "image/jpeg",
                            FileName = "property_3_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 3
                        },
                        new
                        {
                            ImageID = 10,
                            ContentType = "image/jpeg",
                            FileName = "property_4_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 4
                        },
                        new
                        {
                            ImageID = 11,
                            ContentType = "image/jpeg",
                            FileName = "property_4_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 4
                        },
                        new
                        {
                            ImageID = 12,
                            ContentType = "image/jpeg",
                            FileName = "property_4_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 4
                        },
                        new
                        {
                            ImageID = 13,
                            ContentType = "image/jpeg",
                            FileName = "property_5_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 5
                        },
                        new
                        {
                            ImageID = 14,
                            ContentType = "image/jpeg",
                            FileName = "property_5_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 5
                        },
                        new
                        {
                            ImageID = 15,
                            ContentType = "image/jpeg",
                            FileName = "property_5_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 5
                        },
                        new
                        {
                            ImageID = 16,
                            ContentType = "image/jpeg",
                            FileName = "property_6_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 6
                        },
                        new
                        {
                            ImageID = 17,
                            ContentType = "image/jpeg",
                            FileName = "property_6_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 6
                        },
                        new
                        {
                            ImageID = 18,
                            ContentType = "image/jpeg",
                            FileName = "property_6_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 6
                        },
                        new
                        {
                            ImageID = 19,
                            ContentType = "image/jpeg",
                            FileName = "property_7_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 7
                        },
                        new
                        {
                            ImageID = 20,
                            ContentType = "image/jpeg",
                            FileName = "property_7_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 7
                        },
                        new
                        {
                            ImageID = 21,
                            ContentType = "image/jpeg",
                            FileName = "property_7_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 7
                        },
                        new
                        {
                            ImageID = 22,
                            ContentType = "image/jpeg",
                            FileName = "property_8_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 8
                        },
                        new
                        {
                            ImageID = 23,
                            ContentType = "image/jpeg",
                            FileName = "property_8_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 8
                        },
                        new
                        {
                            ImageID = 24,
                            ContentType = "image/jpeg",
                            FileName = "property_8_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 8
                        },
                        new
                        {
                            ImageID = 25,
                            ContentType = "image/jpeg",
                            FileName = "property_9_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 9
                        },
                        new
                        {
                            ImageID = 26,
                            ContentType = "image/jpeg",
                            FileName = "property_9_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 9
                        },
                        new
                        {
                            ImageID = 27,
                            ContentType = "image/jpeg",
                            FileName = "property_9_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 9
                        },
                        new
                        {
                            ImageID = 28,
                            ContentType = "image/jpeg",
                            FileName = "property_10_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 10
                        },
                        new
                        {
                            ImageID = 29,
                            ContentType = "image/jpeg",
                            FileName = "property_10_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 10
                        },
                        new
                        {
                            ImageID = 30,
                            ContentType = "image/jpeg",
                            FileName = "property_10_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 10
                        },
                        new
                        {
                            ImageID = 31,
                            ContentType = "image/jpeg",
                            FileName = "property_11_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 11
                        },
                        new
                        {
                            ImageID = 32,
                            ContentType = "image/jpeg",
                            FileName = "property_11_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 11
                        },
                        new
                        {
                            ImageID = 33,
                            ContentType = "image/jpeg",
                            FileName = "property_11_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 11
                        },
                        new
                        {
                            ImageID = 34,
                            ContentType = "image/jpeg",
                            FileName = "property_12_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 12
                        },
                        new
                        {
                            ImageID = 35,
                            ContentType = "image/jpeg",
                            FileName = "property_12_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 12
                        },
                        new
                        {
                            ImageID = 36,
                            ContentType = "image/jpeg",
                            FileName = "property_12_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 12
                        },
                        new
                        {
                            ImageID = 37,
                            ContentType = "image/jpeg",
                            FileName = "property_13_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 13
                        },
                        new
                        {
                            ImageID = 38,
                            ContentType = "image/jpeg",
                            FileName = "property_13_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 13
                        },
                        new
                        {
                            ImageID = 39,
                            ContentType = "image/jpeg",
                            FileName = "property_13_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 13
                        },
                        new
                        {
                            ImageID = 40,
                            ContentType = "image/jpeg",
                            FileName = "property_14_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 14
                        },
                        new
                        {
                            ImageID = 41,
                            ContentType = "image/jpeg",
                            FileName = "property_14_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 14
                        },
                        new
                        {
                            ImageID = 42,
                            ContentType = "image/jpeg",
                            FileName = "property_14_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 14
                        },
                        new
                        {
                            ImageID = 43,
                            ContentType = "image/jpeg",
                            FileName = "property_15_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 15
                        },
                        new
                        {
                            ImageID = 44,
                            ContentType = "image/jpeg",
                            FileName = "property_15_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 15
                        },
                        new
                        {
                            ImageID = 45,
                            ContentType = "image/jpeg",
                            FileName = "property_15_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 15
                        },
                        new
                        {
                            ImageID = 46,
                            ContentType = "image/jpeg",
                            FileName = "property_16_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 16
                        },
                        new
                        {
                            ImageID = 47,
                            ContentType = "image/jpeg",
                            FileName = "property_16_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 16
                        },
                        new
                        {
                            ImageID = 48,
                            ContentType = "image/jpeg",
                            FileName = "property_16_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 16
                        },
                        new
                        {
                            ImageID = 49,
                            ContentType = "image/jpeg",
                            FileName = "property_17_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 17
                        },
                        new
                        {
                            ImageID = 50,
                            ContentType = "image/jpeg",
                            FileName = "property_17_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 17
                        },
                        new
                        {
                            ImageID = 51,
                            ContentType = "image/jpeg",
                            FileName = "property_17_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 17
                        },
                        new
                        {
                            ImageID = 52,
                            ContentType = "image/jpeg",
                            FileName = "property_18_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 18
                        },
                        new
                        {
                            ImageID = 53,
                            ContentType = "image/jpeg",
                            FileName = "property_18_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 18
                        },
                        new
                        {
                            ImageID = 54,
                            ContentType = "image/jpeg",
                            FileName = "property_18_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 18
                        },
                        new
                        {
                            ImageID = 55,
                            ContentType = "image/jpeg",
                            FileName = "property_19_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 19
                        },
                        new
                        {
                            ImageID = 56,
                            ContentType = "image/jpeg",
                            FileName = "property_19_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 19
                        },
                        new
                        {
                            ImageID = 57,
                            ContentType = "image/jpeg",
                            FileName = "property_19_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 19
                        },
                        new
                        {
                            ImageID = 58,
                            ContentType = "image/jpeg",
                            FileName = "property_20_image_2.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 20
                        },
                        new
                        {
                            ImageID = 59,
                            ContentType = "image/jpeg",
                            FileName = "property_20_image_3.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 20
                        },
                        new
                        {
                            ImageID = 60,
                            ContentType = "image/jpeg",
                            FileName = "property_20_image_1.jpg",
                            ImageData = new byte[] { 255, 216, 255, 224 },
                            PropertyID = 20
                        });
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ListingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerCustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("SizeOfHouse")
                        .HasColumnType("REAL");

                    b.HasKey("PropertyID");

                    b.HasIndex("OwnerCustomerID");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyID = 1,
                            Bathrooms = 1,
                            Bedrooms = 4,
                            BuildYear = 2022,
                            City = "Richmond",
                            Country = "Canada",
                            CurrentStatus = "Rented",
                            Description = "Beautiful Duplex in a great neighborhood. Built in 2014.",
                            ListingDate = new DateTime(2025, 3, 14, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(1620),
                            OwnerCustomerID = 11,
                            PostalCode = "V1B8V3",
                            PropertyAddress = "6122 O Ave",
                            PropertyType = "Condo",
                            Province = "BC",
                            RentalPrice = 2560m,
                            SizeOfHouse = 3315.0
                        },
                        new
                        {
                            PropertyID = 2,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            BuildYear = 2009,
                            City = "Vancouver",
                            Country = "Canada",
                            CurrentStatus = "Sold",
                            Description = "Beautiful Condo in a great neighborhood. Built in 2008.",
                            ListingDate = new DateTime(2025, 3, 12, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2500),
                            OwnerCustomerID = 1,
                            PostalCode = "V4D8L7",
                            PropertyAddress = "8806 E Ave",
                            PropertyType = "Apartment",
                            Province = "BC",
                            SellingPrice = 503405m,
                            SizeOfHouse = 1107.0
                        },
                        new
                        {
                            PropertyID = 3,
                            Bathrooms = 4,
                            Bedrooms = 4,
                            BuildYear = 2019,
                            City = "New Westminster",
                            Country = "Canada",
                            CurrentStatus = "For Rent",
                            Description = "Beautiful Townhouse in a great neighborhood. Built in 2020.",
                            ListingDate = new DateTime(2025, 3, 10, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2510),
                            OwnerCustomerID = 4,
                            PostalCode = "V4W7L1",
                            PropertyAddress = "4501 Y Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            RentalPrice = 3264m,
                            SizeOfHouse = 3596.0
                        },
                        new
                        {
                            PropertyID = 4,
                            Bathrooms = 2,
                            Bedrooms = 4,
                            BuildYear = 1984,
                            City = "North Vancouver",
                            Country = "Canada",
                            CurrentStatus = "Sold",
                            Description = "Beautiful Duplex in a great neighborhood. Built in 2019.",
                            ListingDate = new DateTime(2025, 3, 13, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2520),
                            OwnerCustomerID = 14,
                            PostalCode = "V7Y9R6",
                            PropertyAddress = "8645 R Ave",
                            PropertyType = "House",
                            Province = "BC",
                            SellingPrice = 755236m,
                            SizeOfHouse = 3679.0
                        },
                        new
                        {
                            PropertyID = 5,
                            Bathrooms = 2,
                            Bedrooms = 1,
                            BuildYear = 2021,
                            City = "Richmond",
                            Country = "Canada",
                            CurrentStatus = "For Rent",
                            Description = "Beautiful Townhouse in a great neighborhood. Built in 1986.",
                            ListingDate = new DateTime(2025, 2, 24, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2530),
                            OwnerCustomerID = 13,
                            PostalCode = "V7R1P6",
                            PropertyAddress = "2477 T Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            RentalPrice = 2217m,
                            SizeOfHouse = 1368.0
                        },
                        new
                        {
                            PropertyID = 6,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            BuildYear = 1992,
                            City = "West Vancouver",
                            Country = "Canada",
                            CurrentStatus = "Sold",
                            Description = "Beautiful Duplex in a great neighborhood. Built in 2010.",
                            ListingDate = new DateTime(2025, 2, 24, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2530),
                            OwnerCustomerID = 15,
                            PostalCode = "V3G5S8",
                            PropertyAddress = "6199 M Ave",
                            PropertyType = "Condo",
                            Province = "BC",
                            SellingPrice = 767165m,
                            SizeOfHouse = 3623.0
                        },
                        new
                        {
                            PropertyID = 7,
                            Bathrooms = 4,
                            Bedrooms = 3,
                            BuildYear = 2018,
                            City = "Surrey",
                            Country = "Canada",
                            CurrentStatus = "For Sale",
                            Description = "Beautiful Townhouse in a great neighborhood. Built in 2014.",
                            ListingDate = new DateTime(2025, 2, 27, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2540),
                            OwnerCustomerID = 2,
                            PostalCode = "V5M6O5",
                            PropertyAddress = "2066 Q Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            SellingPrice = 604733m,
                            SizeOfHouse = 4971.0
                        },
                        new
                        {
                            PropertyID = 8,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            BuildYear = 1992,
                            City = "Coquitlam",
                            Country = "Canada",
                            CurrentStatus = "For Sale",
                            Description = "Beautiful Apartment in a great neighborhood. Built in 1985.",
                            ListingDate = new DateTime(2025, 3, 9, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2560),
                            OwnerCustomerID = 13,
                            PostalCode = "V8G2G3",
                            PropertyAddress = "9332 G Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            SellingPrice = 1835123m,
                            SizeOfHouse = 1986.0
                        },
                        new
                        {
                            PropertyID = 9,
                            Bathrooms = 2,
                            Bedrooms = 5,
                            BuildYear = 2012,
                            City = "Vancouver",
                            Country = "Canada",
                            CurrentStatus = "For Sale",
                            Description = "Beautiful Apartment in a great neighborhood. Built in 1997.",
                            ListingDate = new DateTime(2025, 3, 16, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2560),
                            OwnerCustomerID = 1,
                            PostalCode = "V4J7Q2",
                            PropertyAddress = "8773 W Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            SellingPrice = 582731m,
                            SizeOfHouse = 1976.0
                        },
                        new
                        {
                            PropertyID = 10,
                            Bathrooms = 1,
                            Bedrooms = 3,
                            BuildYear = 1983,
                            City = "Coquitlam",
                            Country = "Canada",
                            CurrentStatus = "Rented",
                            Description = "Beautiful Apartment in a great neighborhood. Built in 2000.",
                            ListingDate = new DateTime(2025, 3, 8, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2570),
                            OwnerCustomerID = 19,
                            PostalCode = "V6H8N5",
                            PropertyAddress = "7649 T Ave",
                            PropertyType = "Condo",
                            Province = "BC",
                            RentalPrice = 4626m,
                            SizeOfHouse = 4202.0
                        },
                        new
                        {
                            PropertyID = 11,
                            Bathrooms = 1,
                            Bedrooms = 2,
                            BuildYear = 1984,
                            City = "Langley",
                            Country = "Canada",
                            CurrentStatus = "For Rent",
                            Description = "Beautiful Townhouse in a great neighborhood. Built in 2000.",
                            ListingDate = new DateTime(2025, 3, 16, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2580),
                            OwnerCustomerID = 18,
                            PostalCode = "V7C4X7",
                            PropertyAddress = "4015 F Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            RentalPrice = 1584m,
                            SizeOfHouse = 3630.0
                        },
                        new
                        {
                            PropertyID = 12,
                            Bathrooms = 2,
                            Bedrooms = 1,
                            BuildYear = 2003,
                            City = "North Vancouver",
                            Country = "Canada",
                            CurrentStatus = "Rented",
                            Description = "Beautiful Apartment in a great neighborhood. Built in 2011.",
                            ListingDate = new DateTime(2025, 3, 7, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2580),
                            OwnerCustomerID = 13,
                            PostalCode = "V2F6O5",
                            PropertyAddress = "7468 N Ave",
                            PropertyType = "Condo",
                            Province = "BC",
                            RentalPrice = 3149m,
                            SizeOfHouse = 3644.0
                        },
                        new
                        {
                            PropertyID = 13,
                            Bathrooms = 4,
                            Bedrooms = 5,
                            BuildYear = 1999,
                            City = "Burnaby",
                            Country = "Canada",
                            CurrentStatus = "Rented",
                            Description = "Beautiful House in a great neighborhood. Built in 2002.",
                            ListingDate = new DateTime(2025, 2, 28, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2590),
                            OwnerCustomerID = 15,
                            PostalCode = "V2P4V5",
                            PropertyAddress = "1005 W Ave",
                            PropertyType = "Apartment",
                            Province = "BC",
                            RentalPrice = 3880m,
                            SizeOfHouse = 1848.0
                        },
                        new
                        {
                            PropertyID = 14,
                            Bathrooms = 3,
                            Bedrooms = 2,
                            BuildYear = 2014,
                            City = "North Vancouver",
                            Country = "Canada",
                            CurrentStatus = "Rented",
                            Description = "Beautiful Duplex in a great neighborhood. Built in 2022.",
                            ListingDate = new DateTime(2025, 3, 1, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2590),
                            OwnerCustomerID = 11,
                            PostalCode = "V6R4G9",
                            PropertyAddress = "9916 U Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            RentalPrice = 3156m,
                            SizeOfHouse = 1263.0
                        },
                        new
                        {
                            PropertyID = 15,
                            Bathrooms = 4,
                            Bedrooms = 5,
                            BuildYear = 2010,
                            City = "Delta",
                            Country = "Canada",
                            CurrentStatus = "Rented",
                            Description = "Beautiful Duplex in a great neighborhood. Built in 2022.",
                            ListingDate = new DateTime(2025, 3, 14, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2600),
                            OwnerCustomerID = 16,
                            PostalCode = "V5H3Z2",
                            PropertyAddress = "5072 Y Ave",
                            PropertyType = "House",
                            Province = "BC",
                            RentalPrice = 4360m,
                            SizeOfHouse = 4347.0
                        },
                        new
                        {
                            PropertyID = 16,
                            Bathrooms = 3,
                            Bedrooms = 1,
                            BuildYear = 1994,
                            City = "Vancouver",
                            Country = "Canada",
                            CurrentStatus = "For Sale",
                            Description = "Beautiful Townhouse in a great neighborhood. Built in 2015.",
                            ListingDate = new DateTime(2025, 3, 1, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2610),
                            OwnerCustomerID = 13,
                            PostalCode = "V1H6C1",
                            PropertyAddress = "4302 Q Ave",
                            PropertyType = "Apartment",
                            Province = "BC",
                            SellingPrice = 1231073m,
                            SizeOfHouse = 4557.0
                        },
                        new
                        {
                            PropertyID = 17,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            BuildYear = 1994,
                            City = "Delta",
                            Country = "Canada",
                            CurrentStatus = "Sold",
                            Description = "Beautiful Duplex in a great neighborhood. Built in 2022.",
                            ListingDate = new DateTime(2025, 3, 12, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2610),
                            OwnerCustomerID = 13,
                            PostalCode = "V9O1L4",
                            PropertyAddress = "425 R Ave",
                            PropertyType = "Townhouse",
                            Province = "BC",
                            SellingPrice = 571415m,
                            SizeOfHouse = 2341.0
                        },
                        new
                        {
                            PropertyID = 18,
                            Bathrooms = 3,
                            Bedrooms = 2,
                            BuildYear = 1985,
                            City = "Surrey",
                            Country = "Canada",
                            CurrentStatus = "Sold",
                            Description = "Beautiful House in a great neighborhood. Built in 2015.",
                            ListingDate = new DateTime(2025, 3, 16, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2620),
                            OwnerCustomerID = 2,
                            PostalCode = "V8I3K5",
                            PropertyAddress = "7181 C Ave",
                            PropertyType = "House",
                            Province = "BC",
                            SellingPrice = 1328258m,
                            SizeOfHouse = 1780.0
                        },
                        new
                        {
                            PropertyID = 19,
                            Bathrooms = 1,
                            Bedrooms = 4,
                            BuildYear = 1990,
                            City = "Burnaby",
                            Country = "Canada",
                            CurrentStatus = "For Rent",
                            Description = "Beautiful Condo in a great neighborhood. Built in 1980.",
                            ListingDate = new DateTime(2025, 3, 14, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2630),
                            OwnerCustomerID = 13,
                            PostalCode = "V1M1L6",
                            PropertyAddress = "6780 D Ave",
                            PropertyType = "Apartment",
                            Province = "BC",
                            RentalPrice = 2241m,
                            SizeOfHouse = 3845.0
                        },
                        new
                        {
                            PropertyID = 20,
                            Bathrooms = 2,
                            Bedrooms = 3,
                            BuildYear = 1984,
                            City = "Richmond",
                            Country = "Canada",
                            CurrentStatus = "Sold",
                            Description = "Beautiful Apartment in a great neighborhood. Built in 1993.",
                            ListingDate = new DateTime(2025, 2, 20, 1, 31, 31, 578, DateTimeKind.Local).AddTicks(2630),
                            OwnerCustomerID = 3,
                            PostalCode = "V1T7I2",
                            PropertyAddress = "8036 S Ave",
                            PropertyType = "House",
                            Province = "BC",
                            SellingPrice = 1557945m,
                            SizeOfHouse = 3152.0
                        });
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.PropertyAmenities", b =>
                {
                    b.Property<int>("PropertyAmenitiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AirConditioning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cooktop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dishwasher")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dryer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Elevator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FireSprinklerSystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FitnessRoom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Heating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Locker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Microwave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherAmenities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParkingLot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Refrigerator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SecuritySystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SwimmingPool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Washer")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyAmenitiesID");

                    b.HasIndex("PropertyID")
                        .IsUnique();

                    b.ToTable("PropertyAmenities");

                    b.HasData(
                        new
                        {
                            PropertyAmenitiesID = 1,
                            AirConditioning = false,
                            Cooktop = false,
                            Dishwasher = false,
                            Dryer = true,
                            Elevator = false,
                            FireSprinklerSystem = true,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 1,
                            Refrigerator = true,
                            SecuritySystem = false,
                            SwimmingPool = true,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 2,
                            AirConditioning = true,
                            Cooktop = true,
                            Dishwasher = true,
                            Dryer = true,
                            Elevator = false,
                            FireSprinklerSystem = false,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = false,
                            Microwave = false,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 2,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = false,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 3,
                            AirConditioning = true,
                            Cooktop = false,
                            Dishwasher = true,
                            Dryer = true,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = true,
                            Microwave = false,
                            OtherAmenities = "",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 3,
                            Refrigerator = true,
                            SecuritySystem = false,
                            SwimmingPool = false,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 4,
                            AirConditioning = true,
                            Cooktop = true,
                            Dishwasher = true,
                            Dryer = true,
                            Elevator = false,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = false,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "",
                            ParkingLot = true,
                            PetFriendly = true,
                            PropertyID = 4,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = true,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 5,
                            AirConditioning = true,
                            Cooktop = false,
                            Dishwasher = false,
                            Dryer = false,
                            Elevator = false,
                            FireSprinklerSystem = false,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = false,
                            Microwave = false,
                            OtherAmenities = "",
                            ParkingLot = false,
                            PetFriendly = true,
                            PropertyID = 5,
                            Refrigerator = false,
                            SecuritySystem = false,
                            SwimmingPool = true,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 6,
                            AirConditioning = false,
                            Cooktop = false,
                            Dishwasher = false,
                            Dryer = true,
                            Elevator = false,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "",
                            ParkingLot = false,
                            PetFriendly = true,
                            PropertyID = 6,
                            Refrigerator = false,
                            SecuritySystem = false,
                            SwimmingPool = false,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 7,
                            AirConditioning = false,
                            Cooktop = true,
                            Dishwasher = true,
                            Dryer = false,
                            Elevator = false,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = true,
                            PetFriendly = true,
                            PropertyID = 7,
                            Refrigerator = false,
                            SecuritySystem = true,
                            SwimmingPool = false,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 8,
                            AirConditioning = true,
                            Cooktop = true,
                            Dishwasher = true,
                            Dryer = false,
                            Elevator = false,
                            FireSprinklerSystem = true,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = false,
                            Microwave = false,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 8,
                            Refrigerator = true,
                            SecuritySystem = false,
                            SwimmingPool = false,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 9,
                            AirConditioning = false,
                            Cooktop = false,
                            Dishwasher = false,
                            Dryer = false,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = true,
                            Heating = false,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 9,
                            Refrigerator = true,
                            SecuritySystem = false,
                            SwimmingPool = false,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 10,
                            AirConditioning = false,
                            Cooktop = false,
                            Dishwasher = false,
                            Dryer = true,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "",
                            ParkingLot = true,
                            PetFriendly = false,
                            PropertyID = 10,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = true,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 11,
                            AirConditioning = false,
                            Cooktop = false,
                            Dishwasher = true,
                            Dryer = false,
                            Elevator = true,
                            FireSprinklerSystem = false,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "",
                            ParkingLot = false,
                            PetFriendly = true,
                            PropertyID = 11,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = false,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 12,
                            AirConditioning = true,
                            Cooktop = true,
                            Dishwasher = false,
                            Dryer = true,
                            Elevator = true,
                            FireSprinklerSystem = false,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = false,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = true,
                            PetFriendly = true,
                            PropertyID = 12,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = true,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 13,
                            AirConditioning = true,
                            Cooktop = false,
                            Dishwasher = false,
                            Dryer = true,
                            Elevator = false,
                            FireSprinklerSystem = false,
                            FitnessRoom = false,
                            Heating = false,
                            Locker = true,
                            Microwave = false,
                            OtherAmenities = "",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 13,
                            Refrigerator = false,
                            SecuritySystem = false,
                            SwimmingPool = false,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 14,
                            AirConditioning = false,
                            Cooktop = true,
                            Dishwasher = false,
                            Dryer = false,
                            Elevator = true,
                            FireSprinklerSystem = false,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = false,
                            Microwave = true,
                            OtherAmenities = "",
                            ParkingLot = true,
                            PetFriendly = false,
                            PropertyID = 14,
                            Refrigerator = true,
                            SecuritySystem = false,
                            SwimmingPool = false,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 15,
                            AirConditioning = false,
                            Cooktop = true,
                            Dishwasher = true,
                            Dryer = true,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 15,
                            Refrigerator = false,
                            SecuritySystem = true,
                            SwimmingPool = false,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 16,
                            AirConditioning = false,
                            Cooktop = false,
                            Dishwasher = true,
                            Dryer = false,
                            Elevator = false,
                            FireSprinklerSystem = false,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = false,
                            Microwave = false,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 16,
                            Refrigerator = true,
                            SecuritySystem = false,
                            SwimmingPool = true,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 17,
                            AirConditioning = true,
                            Cooktop = false,
                            Dishwasher = true,
                            Dryer = false,
                            Elevator = false,
                            FireSprinklerSystem = false,
                            FitnessRoom = true,
                            Heating = true,
                            Locker = true,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = true,
                            PetFriendly = true,
                            PropertyID = 17,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = true,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 18,
                            AirConditioning = true,
                            Cooktop = true,
                            Dishwasher = false,
                            Dryer = true,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = true,
                            Heating = false,
                            Locker = false,
                            Microwave = true,
                            OtherAmenities = "Close to public transport, shopping center nearby",
                            ParkingLot = false,
                            PetFriendly = false,
                            PropertyID = 18,
                            Refrigerator = true,
                            SecuritySystem = true,
                            SwimmingPool = false,
                            Washer = false
                        },
                        new
                        {
                            PropertyAmenitiesID = 19,
                            AirConditioning = true,
                            Cooktop = false,
                            Dishwasher = true,
                            Dryer = true,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = true,
                            Microwave = false,
                            OtherAmenities = "",
                            ParkingLot = false,
                            PetFriendly = true,
                            PropertyID = 19,
                            Refrigerator = false,
                            SecuritySystem = true,
                            SwimmingPool = true,
                            Washer = true
                        },
                        new
                        {
                            PropertyAmenitiesID = 20,
                            AirConditioning = false,
                            Cooktop = true,
                            Dishwasher = false,
                            Dryer = false,
                            Elevator = true,
                            FireSprinklerSystem = true,
                            FitnessRoom = false,
                            Heating = true,
                            Locker = true,
                            Microwave = false,
                            OtherAmenities = "",
                            ParkingLot = true,
                            PetFriendly = false,
                            PropertyID = 20,
                            Refrigerator = false,
                            SecuritySystem = true,
                            SwimmingPool = false,
                            Washer = false
                        });
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.RentalContract", b =>
                {
                    b.Property<int>("RentalContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerCustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantCustomerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RentalContractID");

                    b.HasIndex("OwnerCustomerID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("TenantCustomerID");

                    b.ToTable("RentalContracts");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.SalesContract", b =>
                {
                    b.Property<int>("SalesContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerCustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerCustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SalesContractID");

                    b.HasIndex("BuyerCustomerID");

                    b.HasIndex("OwnerCustomerID");

                    b.HasIndex("PropertyID");

                    b.ToTable("SalesContracts");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.Image", b =>
                {
                    b.HasOne("RealEstateAgencySystem.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.Property", b =>
                {
                    b.HasOne("RealEstateAgencySystem.Models.Customer", "Owner")
                        .WithMany("OwnedProperties")
                        .HasForeignKey("OwnerCustomerID");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.PropertyAmenities", b =>
                {
                    b.HasOne("RealEstateAgencySystem.Models.Property", "Property")
                        .WithOne("PropertyAmenities")
                        .HasForeignKey("RealEstateAgencySystem.Models.PropertyAmenities", "PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.RentalContract", b =>
                {
                    b.HasOne("RealEstateAgencySystem.Models.Customer", "OwnerCustomer")
                        .WithMany("RentalsAsOwner")
                        .HasForeignKey("OwnerCustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateAgencySystem.Models.Property", "Property")
                        .WithMany("RentalContracts")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateAgencySystem.Models.Customer", "TenantCustomer")
                        .WithMany("RentalsAsTenant")
                        .HasForeignKey("TenantCustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerCustomer");

                    b.Navigation("Property");

                    b.Navigation("TenantCustomer");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.SalesContract", b =>
                {
                    b.HasOne("RealEstateAgencySystem.Models.Customer", "BuyerCustomer")
                        .WithMany("SalesAsBuyer")
                        .HasForeignKey("BuyerCustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateAgencySystem.Models.Customer", "OwnerCustomer")
                        .WithMany("SalesAsOwner")
                        .HasForeignKey("OwnerCustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateAgencySystem.Models.Property", "Property")
                        .WithMany("SalesContracts")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyerCustomer");

                    b.Navigation("OwnerCustomer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.Customer", b =>
                {
                    b.Navigation("OwnedProperties");

                    b.Navigation("RentalsAsOwner");

                    b.Navigation("RentalsAsTenant");

                    b.Navigation("SalesAsBuyer");

                    b.Navigation("SalesAsOwner");
                });

            modelBuilder.Entity("RealEstateAgencySystem.Models.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PropertyAmenities")
                        .IsRequired();

                    b.Navigation("RentalContracts");

                    b.Navigation("SalesContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
